### ISSUE TITLE
Android linking resource file failed

### ISSUE THREAD

**Issue by Presheda** [PaystackHQ/paystack-android#73] opened 2019-08-02 15:47 UTC
![Screenshot (2)](https://user-images.githubusercontent.com/26353504/62381923-7103f880-b544-11e9-96aa-ff4aa3c7e119.png)

if you are getting the error above, its because there is another dependency the SDK is using that was not mentioned in the documentation. the name of the library is **co.paystack.android.design.widget.PinPadView**

to fix this error simply add 
**implementation 'co.paystack.android.design.widget:pinpad:1.0.1'** to your build.gradle file.

here is the link for updates and reference 
https://github.com/PaystackHQ/library-android-pinpad

**Comment by steveamaza** [comment] 2019-08-02 15:49
@Presheda please provide more information. At what point did this happen

**Comment by ibrahimlawal** [comment] 2019-08-02 15:49
Duplicate of #69 

We are investigating what seems to be an incompatibility with "jetified".

**Closed by ibrahimlawal** 2019-08-02 15:49 UTC

**Comment by Presheda** [comment] 2019-08-02 15:50
i think i found a solution already

**Comment by ibrahimlawal** [comment] 2019-08-02 15:56
Cooool, please share @Presheda

**Comment by ibrahimlawal** [comment] 2019-08-02 15:56
Perhaps on #69 so those following it can benefit

**Comment by Presheda** [comment] 2019-08-02 16:08
i just shared it. i updated the first comment.
adding the following line to the build.gradle file

**implementation 'co.paystack.android.design.widget:pinpad:1.0.1'**

**Comment by matthitachi** [comment] 2020-02-28 20:30
please any solution with what seems to be an incompatibility with "jetified"???
